name: GitHub Demo Test

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Pacman

        strategy:
            matrix:
                python-version: [3.13.3]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Display Python version
              run: python --version
            - name: Run Pacman tests
              run: |
                  echo "Running tests for Pacman game"
                  ls -la
